Added in sonarscan job to pr-checks
dvsa/cvs-svc-test-stations pull request #121
Opened 2023-12-11 16:46 UTC by TaylorHalf

Added in sonarscan job to pr-checks

2023-12-14 16:01 UTC, hamiltonrossbjss approved these changes

2023-12-18 01:01 UTC, JoshCarter-ops requested changes

2023-12-18 01:01 UTC, JoshCarter-ops commented on .github/workflows/pr-checks.yml
> +          role-session-name: 'cvs-app-vtm'
this repo name

2023-12-18 09:43 UTC, JoshCarter-ops approved these changes

2023-12-21 11:01 UTC, merged