(BE) Update VTA dependencies
dvsa/cvs-svc-test-stations pull request #67
Opened 2022-01-28 13:19 UTC by Daniel-Searle

## (BE) Update VTA dependencies

One line description
[link to ticket number](https://jira.dvsacloud.uk/browse/VTA-292)

## Checklist

- [ ] Code has been tested manually
- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Squashed commit contains the JIRA ticket number

2022-02-01 09:16 UTC, cb-cs requested changes
@Daniel-Searle please can you add the --prod flaf on audit script

2022-02-02 11:40 UTC, m-coslett reviewed
Please add the ticket number to the PR title as per the usual format

2022-02-07 08:56 UTC, cb-cs approved these changes

2022-02-07 10:18 UTC, m-coslett approved these changes

2022-02-24 15:33 UTC, merged